apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default # Specify the namespace for the Application resource
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nkarumanchi27/argo-kargo.git
    path: charts/grafana
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana # Deploy the resources to the argocd namespace
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
