apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default # Specify the namespace for the Application resource
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://artifacthub.io/charts/nkarumanchi27/na-helm-charts
    path: my-nginx
    targetRevision: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx # Deploy the resources to the argocd namespace
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true